/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module Mux_16x1_NBits #(
    parameter Bits = 2
)
(
    input [3:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    input [(Bits - 1):0] in_8,
    input [(Bits - 1):0] in_9,
    input [(Bits - 1):0] in_10,
    input [(Bits - 1):0] in_11,
    input [(Bits - 1):0] in_12,
    input [(Bits - 1):0] in_13,
    input [(Bits - 1):0] in_14,
    input [(Bits - 1):0] in_15,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Decoder4 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    output out_8,
    output out_9,
    output out_10,
    output out_11,
    output out_12,
    output out_13,
    output out_14,
    output out_15,
    input [3:0] sel
);
    assign out_0 = (sel == 4'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 4'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 4'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 4'h3)? 1'b1 : 1'b0;
    assign out_4 = (sel == 4'h4)? 1'b1 : 1'b0;
    assign out_5 = (sel == 4'h5)? 1'b1 : 1'b0;
    assign out_6 = (sel == 4'h6)? 1'b1 : 1'b0;
    assign out_7 = (sel == 4'h7)? 1'b1 : 1'b0;
    assign out_8 = (sel == 4'h8)? 1'b1 : 1'b0;
    assign out_9 = (sel == 4'h9)? 1'b1 : 1'b0;
    assign out_10 = (sel == 4'ha)? 1'b1 : 1'b0;
    assign out_11 = (sel == 4'hb)? 1'b1 : 1'b0;
    assign out_12 = (sel == 4'hc)? 1'b1 : 1'b0;
    assign out_13 = (sel == 4'hd)? 1'b1 : 1'b0;
    assign out_14 = (sel == 4'he)? 1'b1 : 1'b0;
    assign out_15 = (sel == 4'hf)? 1'b1 : 1'b0;
endmodule


module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Decoder2 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    input [1:0] sel
);
    assign out_0 = (sel == 2'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 2'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 2'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 2'h3)? 1'b1 : 1'b0;
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule


module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module DIG_Mul_unsigned #(
    parameter Bits = 1
)
(
    
      input [(Bits-1):0] a,
      input [(Bits-1):0] b,
      output [(Bits*2-1):0] mul
    
);
    assign mul = a * b;
endmodule


module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_16x1
(
    input [3:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    input in_8,
    input in_9,
    input in_10,
    input in_11,
    input in_12,
    input in_13,
    input in_14,
    input in_15,
    output reg out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_CounterPreset #(
    parameter Bits = 2,
    parameter maxValue = 4
)
(
    input C,
    input en,
    input clr,
    input dir,
    input [(Bits-1):0] in,
    input ld,
    output [(Bits-1):0] out,
    output ovf
);

    reg [(Bits-1):0] count = 'h0;

    function [(Bits-1):0] maxVal (input [(Bits-1):0] maxv);
        if (maxv == 0)
            maxVal = (1 << Bits) - 1;
        else
            maxVal = maxv;
    endfunction

    assign out = count;
    assign ovf = ((count == maxVal(maxValue) & dir == 1'b0)
                  | (count == 'b0 & dir == 1'b1))? en : 1'b0;

    always @ (posedge C) begin
        if (clr == 1'b1)
            count <= 'h0;
        else if (ld == 1'b1)
            count <= in;
        else if (en == 1'b1) begin
            if (dir == 1'b0) begin
                if (count == maxVal(maxValue))
                    count <= 'h0;
                else
                    count <= count + 1'b1;
            end
            else begin
                if (count == 'h0)
                    count <= maxVal(maxValue);
                else
                    count <= count - 1;
            end
        end
    end
endmodule


module nna8v2_mpu_mux (
  input clk,
  input [7:0] data_in,
  input rst, // Reset the processor
  output [15:0] addr_out,
  output [7:0] data_out, // byte to be written
  output r, // The cpu wants to read the value at the address addr_out into data_in
  output w, // The cpu wants to write the value of data_out to the address addr_out
  output brk
);
  wire [7:0] s0;
  wire [3:0] arg;
  wire [3:0] curop;
  wire [1:0] arg1;
  wire [1:0] arg0;
  wire s1;
  wire s2;
  wire flag_out;
  wire [7:0] regin;
  wire \~clock ;
  wire s3;
  wire [7:0] regout_r0;
  wire s4;
  wire [7:0] s5;
  wire s6;
  wire [7:0] s7;
  wire s8;
  wire [7:0] s9;
  wire [1:0] selreg;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire [7:0] data_out_temp;
  wire [7:0] s14;
  wire [7:0] s15;
  wire [7:0] inc_rslt;
  wire inc_flag;
  wire [7:0] dec_rslt;
  wire dec_flag;
  wire xcycle;
  wire s16;
  wire [7:0] pc_next;
  wire s17;
  wire mpb;
  wire [7:0] pc;
  wire s18;
  wire lil;
  wire lih;
  wire [7:0] lil_rslt;
  wire [7:0] lih_rslt;
  wire s19;
  wire s20;
  wire [7:0] s21;
  wire s22;
  wire mwr;
  wire w_temp;
  wire mrd;
  wire r_temp;
  wire s23;
  wire xcycle_next;
  wire s24;
  wire pc_write;
  wire s25;
  wire [7:0] pb;
  wire s26;
  wire [7:0] db;
  wire s27;
  wire [3:0] co;
  wire sin;
  wire eq;
  wire gt;
  wire flg;
  wire bra;
  wire mco;
  wire mov;
  wire cal;
  wire \xor ;
  wire inc;
  wire dec;
  wire s28;
  wire s29;
  wire s30;
  wire nop;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire jmp;
  wire eq_flag;
  wire gt_flag;
  wire flg_flag;
  wire cal_flag;
  wire reg_we;
  wire [7:0] add_rslt;
  wire add_carry;
  wire [7:0] sub_rslt;
  wire sub_carry;
  wire [15:0] s35;
  wire [7:0] mul_rslt;
  wire [7:0] and_rslt;
  wire [7:0] or_rslt;
  wire [7:0] not_rslt;
  wire [7:0] xor_rslt;
  wire co_add;
  wire co_sub;
  wire [7:0] s36;
  wire [7:0] s37;
  wire [7:0] s38;
  wire [7:0] cal_rslt;
  wire [7:0] s39;
  wire s40;
  wire [7:0] bank;
  wire [7:0] addr;
  assign s24 = ~ clk;
  assign s2 = ~ clk;
  assign s39[0] = rst;
  assign s39[1] = rst;
  assign s39[2] = rst;
  assign s39[3] = rst;
  assign s39[4] = rst;
  assign s39[5] = rst;
  assign s39[6] = rst;
  assign s39[7] = rst;
  assign \~clock  = ~ clk;
  assign s21 = (data_in & ~ s39);
  // flag
  DIG_Register DIG_Register_i0 (
    .D( s1 ),
    .C( s2 ),
    .en( 1'b1 ),
    .Q( flag_out )
  );
  // r0
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i1 (
    .D( regin ),
    .C( \~clock  ),
    .en( s3 ),
    .Q( regout_r0 )
  );
  // r1
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i2 (
    .D( regin ),
    .C( \~clock  ),
    .en( s4 ),
    .Q( s5 )
  );
  // r2
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i3 (
    .D( regin ),
    .C( \~clock  ),
    .en( s6 ),
    .Q( s7 )
  );
  // r3
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i4 (
    .D( regin ),
    .C( \~clock  ),
    .en( s8 ),
    .Q( s9 )
  );
  // curop
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i5 (
    .D( s21 ),
    .C( clk ),
    .en( s22 ),
    .Q( s0 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( xcycle_next ),
    .C( s24 ),
    .Q( xcycle ),
    .\~Q ( s23 )
  );
  // pb
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i7 (
    .D( data_out_temp ),
    .C( \~clock  ),
    .en( s25 ),
    .Q( pb )
  );
  // db
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i8 (
    .D( data_out_temp ),
    .C( \~clock  ),
    .en( s26 ),
    .Q( db )
  );
  // co
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i9 (
    .D( arg ),
    .C( \~clock  ),
    .en( s27 ),
    .Q( co )
  );
  assign s25 = (rst | mpb);
  assign s26 = (rst | (s34 & sin));
  assign s27 = (rst | mco);
  assign s8 = ((s13 & reg_we) | rst);
  assign s6 = ((s12 & reg_we) | rst);
  assign s4 = ((s11 & reg_we) | rst);
  assign s3 = ((s10 & reg_we) | rst);
  assign s22 = (rst | ~ xcycle);
  assign s17 = (pc_write | rst);
  assign pc_write = (((jmp | bra) & ~ flag_out) | rst);
  Mux_16x1_NBits #(
    .Bits(8)
  )
  Mux_16x1_NBits_i10 (
    .sel( curop ),
    .in_0( 8'b0 ),
    .in_1( 8'b0 ),
    .in_2( 8'b0 ),
    .in_3( 8'b0 ),
    .in_4( 8'b0 ),
    .in_5( 8'b0 ),
    .in_6( 8'b0 ),
    .in_7( 8'b0 ),
    .in_8( s21 ),
    .in_9( lil_rslt ),
    .in_10( lih_rslt ),
    .in_11( s14 ),
    .in_12( cal_rslt ),
    .in_13( xor_rslt ),
    .in_14( inc_rslt ),
    .in_15( dec_rslt ),
    .out( regin )
  );
  assign s16 = ~ xcycle;
  Decoder4 Decoder4_i11 (
    .sel( co ),
    .out_0( co_add ),
    .out_1( co_sub )
  );
  assign arg = s0[3:0];
  assign curop = s0[7:4];
  assign lil_rslt[3:0] = arg;
  assign lil_rslt[7:4] = regout_r0[7:4];
  assign lih_rslt[3:0] = regout_r0[3:0];
  assign lih_rslt[7:4] = arg;
  Decoder4 Decoder4_i12 (
    .sel( curop ),
    .out_0( sin ),
    .out_1( eq ),
    .out_2( gt ),
    .out_3( flg ),
    .out_5( bra ),
    .out_6( mco ),
    .out_7( mwr ),
    .out_8( mrd ),
    .out_9( lil ),
    .out_10( lih ),
    .out_11( mov ),
    .out_12( cal ),
    .out_13( \xor  ),
    .out_14( inc ),
    .out_15( dec )
  );
  assign arg1 = arg[1:0];
  assign arg0 = arg[3:2];
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i13 (
    .sel( arg0 ),
    .in_0( regout_r0 ),
    .in_1( s5 ),
    .in_2( s7 ),
    .in_3( s9 ),
    .out( data_out_temp )
  );
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i14 (
    .sel( arg1 ),
    .in_0( regout_r0 ),
    .in_1( s5 ),
    .in_2( s7 ),
    .in_3( s9 ),
    .out( s14 )
  );
  assign s18 = (lil | lih);
  assign w_temp = (xcycle & mwr);
  assign r_temp = (xcycle & mrd);
  assign xcycle_next = (s23 & (mrd | pc_write | mwr));
  Decoder2 Decoder2_i15 (
    .sel( arg0 ),
    .out_0( s28 ),
    .out_1( s29 )
  );
  Decoder2 Decoder2_i16 (
    .sel( arg1 ),
    .out_0( s31 ),
    .out_1( s32 ),
    .out_2( s33 ),
    .out_3( s34 )
  );
  assign s15[1:0] = arg1;
  assign s15[7:2] = 6'b0;
  assign flg_flag = ((~ flag_out & ~ arg0[0]) | (arg0[1] & arg0[0]));
  assign reg_we = (curop[3] & ~ (~ xcycle & mrd));
  assign s37[0] = bra;
  assign s37[1] = bra;
  assign s37[2] = bra;
  assign s37[3] = bra;
  assign s37[4] = bra;
  assign s37[5] = bra;
  assign s37[6] = bra;
  assign s37[7] = bra;
  DIG_Add #(
    .Bits(8)
  )
  DIG_Add_i17 (
    .a( data_out_temp ),
    .b( s15 ),
    .c_i( 1'b1 ),
    .s( inc_rslt ),
    .c_o( inc_flag )
  );
  DIG_Sub #(
    .Bits(8)
  )
  DIG_Sub_i18 (
    .a( data_out_temp ),
    .b( s15 ),
    .c_i( 1'b1 ),
    .s( dec_rslt ),
    .c_o( dec_flag )
  );
  assign selreg[0] = (arg0[0] & ~ s18);
  assign selreg[1] = (arg0[1] & ~ s18);
  CompUnsigned #(
    .Bits(8)
  )
  CompUnsigned_i19 (
    .a( data_out_temp ),
    .b( s14 ),
    .\= ( s19 ),
    .\< ( s20 )
  );
  assign s30 = (sin & s31);
  assign jmp = (s32 & sin);
  assign mpb = (s33 & sin);
  DIG_Add #(
    .Bits(8)
  )
  DIG_Add_i20 (
    .a( data_out_temp ),
    .b( s14 ),
    .c_i( flag_out ),
    .s( add_rslt ),
    .c_o( add_carry )
  );
  DIG_Sub #(
    .Bits(8)
  )
  DIG_Sub_i21 (
    .a( data_out_temp ),
    .b( s14 ),
    .c_i( flag_out ),
    .s( sub_rslt ),
    .c_o( sub_carry )
  );
  DIG_Mul_unsigned #(
    .Bits(8)
  )
  DIG_Mul_unsigned_i22 (
    .a( data_out_temp ),
    .b( s14 ),
    .mul( s35 )
  );
  assign and_rslt = (data_out_temp & s14);
  assign or_rslt = (data_out_temp | s14);
  assign not_rslt = ~ data_out_temp;
  assign xor_rslt = (data_out_temp ^ s14);
  assign s40 = ~ (w_temp | r_temp);
  Decoder2 Decoder2_i23 (
    .sel( selreg ),
    .out_0( s10 ),
    .out_1( s11 ),
    .out_2( s12 ),
    .out_3( s13 )
  );
  assign nop = (s30 & s28);
  assign brk = (s30 & s29);
  assign eq_flag = ~ s19;
  assign gt_flag = ~ s20;
  assign cal_flag = ((co_add & add_carry) | (co_sub & sub_carry) | (~ (co_add | co_sub) & flag_out));
  assign s36[0] = jmp;
  assign s36[1] = jmp;
  assign s36[2] = jmp;
  assign s36[3] = jmp;
  assign s36[4] = jmp;
  assign s36[5] = jmp;
  assign s36[6] = jmp;
  assign s36[7] = jmp;
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i24 (
    .sel( s40 ),
    .in_0( db ),
    .in_1( pb ),
    .out( bank )
  );
  assign mul_rslt = s35[7:0];
  Mux_16x1 Mux_16x1_i25 (
    .sel( curop ),
    .in_0( flag_out ),
    .in_1( eq_flag ),
    .in_2( gt_flag ),
    .in_3( flg_flag ),
    .in_4( flag_out ),
    .in_5( flag_out ),
    .in_6( flag_out ),
    .in_7( flag_out ),
    .in_8( flag_out ),
    .in_9( flag_out ),
    .in_10( flag_out ),
    .in_11( flag_out ),
    .in_12( cal_flag ),
    .in_13( flag_out ),
    .in_14( inc_flag ),
    .in_15( dec_flag ),
    .out( s1 )
  );
  Mux_16x1_NBits #(
    .Bits(8)
  )
  Mux_16x1_NBits_i26 (
    .sel( co ),
    .in_0( add_rslt ),
    .in_1( sub_rslt ),
    .in_2( mul_rslt ),
    .in_3( 8'b0 ),
    .in_4( 8'b0 ),
    .in_5( 8'b0 ),
    .in_6( 8'b0 ),
    .in_7( 8'b0 ),
    .in_8( and_rslt ),
    .in_9( or_rslt ),
    .in_10( not_rslt ),
    .in_11( 8'b0 ),
    .in_12( 8'b0 ),
    .in_13( 8'b0 ),
    .in_14( 8'b0 ),
    .in_15( 8'b0 ),
    .out( cal_rslt )
  );
  // PC
  DIG_CounterPreset #(
    .Bits(8),
    .maxValue(0)
  )
  DIG_CounterPreset_i27 (
    .en( s16 ),
    .C( clk ),
    .dir( 1'b0 ),
    .in( pc_next ),
    .ld( s17 ),
    .clr( mpb ),
    .out( pc )
  );
  assign pc_next = ((data_out_temp & s36) | (s38 & s37));
  assign s38[3:0] = arg;
  assign s38[7:4] = pc[7:4];
  assign addr_out[7:0] = addr;
  assign addr_out[15:8] = bank;
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i28 (
    .sel( xcycle ),
    .in_0( pc ),
    .in_1( s14 ),
    .out( addr )
  );
  assign data_out = data_out_temp;
  assign r = r_temp;
  assign w = w_temp;
endmodule

module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule


module memory_controller (
  input clk,
  input [15:0] addr_in,
  input [3:0] SPI_in,
  input rst,
  input [7:0] data_in,
  input write,
  output [7:0] data_out,
  output data_ready,
  output [3:0] SPI_out, // Output
  output SPI_oe,
  output SPI_cs
);
  wire s0;
  wire [3:0] state;
  wire [7:0] data_out_temp;
  wire data_ready_temp;
  wire [3:0] s1;
  wire [3:0] s2;
  wire [3:0] s3;
  wire [3:0] s4;
  wire [3:0] s5;
  wire [3:0] s6;
  wire [3:0] s7;
  wire [3:0] s8;
  wire s9;
  wire readdata;
  wire [7:0] s10;
  wire [3:0] s11;
  wire [3:0] s12;
  wire s13;
  wire [7:0] cmd;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i0 (
    .sel( write ),
    .in_0( 8'b1011 ),
    .in_1( 8'b10 ),
    .out( cmd )
  );
  assign s3 = addr_in[3:0];
  assign s4 = addr_in[7:4];
  assign s5 = addr_in[11:8];
  assign s6 = addr_in[15:12];
  assign s7 = data_in[3:0];
  assign s8 = data_in[7:4];
  assign s1 = cmd[3:0];
  assign s2 = cmd[7:4];
  Mux_16x1_NBits #(
    .Bits(4)
  )
  Mux_16x1_NBits_i1 (
    .sel( state ),
    .in_0( 4'b0 ),
    .in_1( s1 ),
    .in_2( s2 ),
    .in_3( s3 ),
    .in_4( s4 ),
    .in_5( s5 ),
    .in_6( s6 ),
    .in_7( 4'b0 ),
    .in_8( 4'b0 ),
    .in_9( s7 ),
    .in_10( s8 ),
    .in_11( 4'b0 ),
    .in_12( 4'b0 ),
    .in_13( 4'b0 ),
    .in_14( 4'b0 ),
    .in_15( 4'b0 ),
    .out( SPI_out )
  );
  assign s10[3:0] = s11;
  assign s10[7:4] = SPI_in;
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i2 (
    .sel( data_ready_temp ),
    .in_0( SPI_in ),
    .in_1( s12 ),
    .out( s11 )
  );
  assign SPI_oe = ((s15 | ((s16 | s17) & write)) & ~ rst);
  assign SPI_cs = (~ rst & ~ (s13 | s14));
  assign s0 = (rst | data_ready_temp | (s17 & write));
  DIG_Counter_Nbit #(
    .Bits(4)
  )
  DIG_Counter_Nbit_i3 (
    .en( 1'b1 ),
    .C( clk ),
    .clr( s0 ),
    .out( state )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i4 (
    .a( 4'b1101 ),
    .b( state ),
    .\= ( s9 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i5 (
    .a( 4'b1110 ),
    .b( state ),
    .\= ( data_ready_temp )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i6 (
    .a( state ),
    .b( 4'b0 ),
    .\= ( s13 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i7 (
    .a( state ),
    .b( 4'b1 ),
    .\= ( s14 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i8 (
    .a( state ),
    .b( 4'b1010 ),
    .\< ( s15 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i9 (
    .a( state ),
    .b( 4'b1001 ),
    .\= ( s16 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i10 (
    .a( state ),
    .b( 4'b1010 ),
    .\= ( s17 )
  );
  assign readdata = (s9 | data_ready_temp);
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i11 (
    .D( s10 ),
    .C( clk ),
    .en( readdata ),
    .Q( data_out_temp )
  );
  assign s12 = data_out_temp[3:0];
  assign data_out = data_out_temp;
  assign data_ready = data_ready_temp;
endmodule

module tinynna (
  input rst_n,
  input clk,
  input [7:0] uio_in,
  input [7:0] ui_in,
  output [7:0] uo_out,
  output [7:0] uio_out,
  output [7:0] uio_oe
);
  wire rst;
  wire clk_p;
  wire [7:0] data_in;
  wire [15:0] addr_out;
  wire [7:0] data_out;
  wire s0;
  wire s1;
  wire [3:0] spi_in;
  wire s2;
  wire [3:0] spi_out;
  wire s3;
  wire cs_flash;
  wire [3:0] spi_oe;
  wire const1b0;
  assign uo_out = 8'b0;
  assign const1b0 = 1'b0;
  assign rst = ~ rst_n;
  assign spi_in[0] = uio_in[1];
  assign spi_in[1] = uio_in[2];
  assign spi_in[2] = uio_in[4];
  assign spi_in[3] = uio_in[5];
  nna8v2_mpu_mux nna8v2_mpu_mux_i0 (
    .clk( clk_p ),
    .data_in( data_in ),
    .rst( rst ),
    .addr_out( addr_out ),
    .data_out( data_out ),
    .r( s0 ),
    .w( s1 )
  );
  assign uio_out[0] = ~ cs_flash;
  assign uio_out[1] = spi_out[0];
  assign uio_out[2] = spi_out[1];
  assign uio_out[3] = clk;
  assign uio_out[4] = spi_out[2];
  assign uio_out[5] = spi_out[3];
  assign uio_out[6] = ~ const1b0;
  assign uio_out[7] = ~ const1b0;
  memory_controller memory_controller_i1 (
    .clk( clk ),
    .addr_in( addr_out ),
    .SPI_in( spi_in ),
    .rst( rst ),
    .data_in( data_out ),
    .write( s1 ),
    .data_out( data_in ),
    .data_ready( s2 ),
    .SPI_out( spi_out ),
    .SPI_oe( s3 ),
    .SPI_cs( cs_flash )
  );
  assign clk_p = ((clk & ~ (s0 | s1)) | s2);
  assign spi_oe[0] = s3;
  assign spi_oe[1] = s3;
  assign spi_oe[2] = s3;
  assign spi_oe[3] = s3;
  assign uio_oe[0] = 1'b1;
  assign uio_oe[1] = spi_oe[0];
  assign uio_oe[2] = spi_oe[1];
  assign uio_oe[3] = 1'b1;
  assign uio_oe[4] = spi_oe[2];
  assign uio_oe[5] = spi_oe[3];
  assign uio_oe[6] = 1'b1;
  assign uio_oe[7] = 1'b1;
endmodule
